# Generated by Django 4.2.14 on 2024-09-06 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_profile_age_profile_gender'),
        ('business', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAnalytics',
            fields=[
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='business_analytics', serialize=False, to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Analytics',
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product_analytics', serialize=False, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Analytics',
            },
        ),
        migrations.CreateModel(
            name='ProductViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='analytics.productanalytics')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'verbose_name_plural': 'Product Views',
            },
        ),
        migrations.CreateModel(
            name='ProductBagAdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_add_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bag_adds', to='analytics.productanalytics')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'verbose_name_plural': 'Product Bag Adds',
            },
        ),
        migrations.CreateModel(
            name='BusinessPageViews',
            fields=[
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='business_page_views', serialize=False, to='analytics.businessanalytics')),
                ('view_date', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_page_views', to='profiles.profile')),
            ],
            options={
                'verbose_name_plural': 'Business Page Views',
            },
        ),
    ]
