# Generated by Django 4.2.14 on 2024-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
