# Generated by Django 4.2.14 on 2024-08-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productvariant_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='business',
            field=models.ForeignKey(default='LGNDXDHD', on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='api.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='api.business'),
        ),
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.business'),
        ),
    ]
