# Generated by Django 4.2.14 on 2024-08-29 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_remove_credentials_business'),
        ('api', '0009_remove_business_location_location_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='authentications.credentials'),
        ),
    ]
