# Generated by Django 4.2.14 on 2024-08-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_business_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business',
            new_name='credentials',
        ),
    ]
