# Generated by Django 4.2.14 on 2024-08-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_business_business_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
