import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import NavigationBar from "@/components/NavigationBar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="sm:grid sm:grid-cols-[10%_90%] md:grid-cols-[10%_80%_10%]">
            <NavigationBar />
          <div>
            {children}
          </div>
          <div className="hidden md:block">

          </div>
          
        </main>
        <Toaster />
        </body>
    </html>
  );
}
