# Generated by Django 4.2.14 on 2024-08-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='credentials',
        ),
    ]
