# Generated by Django 4.2.14 on 2024-09-01 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_business_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='business.business'),
        ),
    ]
