# Generated by Django 4.2.14 on 2024-09-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_subscription_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default='Zimbabwe', max_length=30),
        ),
    ]
