# Generated by Django 4.2.14 on 2024-08-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_remove_business_location_location_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api.business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
