# Generated by Django 4.2.14 on 2024-08-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_business_location_location_business_and_more'),
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='business',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api.business'),
        ),
    ]
