# Generated by Django 4.2.14 on 2024-08-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_alter_credentials_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='business',
        ),
    ]
