# Generated by Django 4.2.14 on 2024-08-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_remove_credentials_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
