# Generated by Django 4.2.14 on 2024-08-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_credentials_is_active_credentials_is_staff_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='authentications.credentials'),
        ),
    ]
