# Generated by Django 4.2.14 on 2024-08-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_remove_credentials_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['user'], 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AddField(
            model_name='credentials',
            name='account_type',
            field=models.CharField(choices=[('basic', 'basic'), ('business', 'Business')], default='basic', max_length=20),
        ),
    ]
